_pixellary_inhouse:
    resource: "@PixellaryInhouseBundle/Resources/config/routing.yml"

login:
    pattern:   /login
    defaults:  { _controller: PixellaryInhouseBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout 