pixellary_inhouse:
    pattern:  /
    defaults: { _controller: PixellaryInhouseBundle:Default:index }

pixellary_inhouse_board:
    pattern:  /board
    defaults: { _controller: PixellaryInhouseBundle:Default:board }

pixellary_inhouse_about:
    pattern:  /about
    defaults: { _controller: PixellaryInhouseBundle:Default:about }

pixellary_inhouse_schedule:
    pattern:  /schedule
    defaults: { _controller: PixellaryInhouseBundle:Default:schedule }

pixellary_inhouse_projectsExtended:
    pattern:  /projectsExtended
    defaults: { _controller: PixellaryInhouseBundle:Default:projectsExtended }

pixellary_inhouse_reporting:
    pattern:  /reporting
    defaults: { _controller: PixellaryInhouseBundle:Default:reporting }

pixellary_inhouse_taskList:
    pattern:  /taskList
    defaults: { _controller: PixellaryInhouseBundle:Default:taskList }

pixellary_inhouse_taskForm:
    pattern:  /taskForm
    defaults: { _controller: PixellaryInhouseBundle:Default:taskForm }

pixellary_inhouse_clientList:
    pattern:  /clientList
    defaults: { _controller: PixellaryInhouseBundle:Default:clientList }

pixellary_inhouse_clientForm:
    pattern:  /clientForm
    defaults: { _controller: PixellaryInhouseBundle:Default:clientForm }

pixellary_inhouse_projectList:
    pattern:  /projectList
    defaults: { _controller: PixellaryInhouseBundle:Default:projectList }

pixellary_inhouse_projectForm:
    pattern:  /projectForm
    defaults: { _controller: PixellaryInhouseBundle:Default:projectForm }