pixellary_inhouse:
    pattern:  /
    defaults: { _controller: PixellaryInhouseBundle:Default:index }

pixellary_inhouse_board:
    pattern:  /board
    defaults: { _controller: PixellaryInhouseBundle:Default:board }

pixellary_inhouse_about:
    pattern:  /about
    defaults: { _controller: PixellaryInhouseBundle:Default:about }

pixellary_inhouse_schedule:
    pattern:  /schedule
    defaults: { _controller: PixellaryInhouseBundle:Default:schedule }

pixellary_inhouse_projects:
    pattern:  /projects
    defaults: { _controller: PixellaryInhouseBundle:Default:projects }

pixellary_inhouse_reporting:
    pattern:  /reporting
    defaults: { _controller: PixellaryInhouseBundle:Default:reporting }

taskList:
    pattern:  /tasklist
    defaults: { _controller: PixellaryInhouseBundle:Default:taskList }

taskForm:
    pattern:  /taskform
    defaults: { _controller: PixellaryInhouseBundle:Default:taskForm }